apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: dag-pipeline-dotnet
  annotations:
    workflows.argoproj.io/description: |
      DAG workflow: dotnet build -> test -> push
spec:
  entrypoint: main
  arguments:
   parameters:
      - name: repo
        value: github.com/galsolom/testapp.git
      - name: branch
        value: main
      - name: tag
        value: 0.1
      - name: message
        value: argo-workflows-catalog
  templates:
  - name: main
    dag:
      tasks:
      - name: build
        templateRef: 
          name: kaniko-build
          template: kaniko-build
          clusterScope: true
        arguments:
          parameters:
          - name: repo
            value: "{{workflow.parameters.repo}}"
          - name: branch
            value: "{{workflow.parameters.branch}}"
          - name: tag
            value: "{{workflow.parameters.tag}}"
          - name: message
            value: "{{workflow.parameters.message}}"
      - name: inner-hello1
        depends: "build"
        templateRef:
          name: echo
          template: say
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: "inner-hello1"
      - name: inner-hello2a
        depends: "inner-hello1"
        templateRef:
          name: echo
          template: say
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: "inner-hello2a"
      - name: inner-hello2b
        depends: "inner-hello1"
        templateRef:
          name: echo
          template: say
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: "inner-hello2b"
      - name: inner-hello2c
        depends: "inner-hello2a && inner-hello2b"
        templateRef:
          name: echo
          template: say
          clusterScope: true
        arguments:
          parameters:
          - name: message
            value: "inner-hello2c"