apiVersion: v1
kind: Pod
metadata:
  name: tests
spec:
  containers:
  - name: tests
    image: docker.io/shiranshalev/test:tests0.2
    # args:
    # - "--dockerfile=Dockerfile"
    # - "--context=git://github.com/shiranshalev/testapp.git#refs/heads/main"
    # - "--destination=docker.io/shiranshalev/tests:kaniko0.0.1"
    # volumeMounts:
    # - name: kaniko-secret
    #   mountPath: /kaniko/.docker
  restartPolicy: Never
  # volumes:
  # - name: kaniko-secret
  #   secret:
  #     secretName: kaniko-docker-secret