apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      checkout out from git, build and test a dotnet application.
    workflows.argoproj.io/maintainer: '@gals'
    workflows.argoproj.io/tags: dotnet, git
    workflows.argoproj.io/version: '>= 2.9.0'
  name: dotnet-build-dind
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: repo
        value: https://github.com/galsolom/testapp.git
      - name: branch
        value: main
      - name: tag
        value: 0.1
      - name: output
        value: argo-workflows-catalog
  templates:
    - name: main
      steps:
        - - name: checkout
            template: checkout
        - - name: build
            template: build
        - - name: test
            template: test
        - - name: dind
            template: dind-sidecar
    - name: checkout
      script:
        image: mcr.microsoft.com/dotnet/sdk:5.0
        workingDir: /work
        args:
          - sh
        # use --depth 1 and --single-branch for fastest possible checkout
        source: git clone --depth 1 --single-branch --branch {{workflow.parameters.branch}} {{workflow.parameters.repo}} .
        volumeMounts:
          - mountPath: /work
            name: work
    - name: docker-build-test
      container:
        image: docker:19.03.13
        command: [sh, -c]
        workingDir: /work
        args: ["docker build . -t test:{{workflow.parameters.tag}} && docker run --rm test:{{workflow.parameters.tag}};"]
        env:
        - name: DOCKER_HOST
          value: 127.0.0.1 # need to change to docker build machine ip;
        volumeMounts:
          - mountPath: /work
            name: work
      sidecars:
      - name: dind
        image: docker:19.03.13-dind
        securityContext:
          privileged: true
        mirrorVolumeMounts: true

    
  volumeClaimTemplates:
    # A shared work volume.
    - name: work
      metadata:
        name: work
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClass: "openebs-cstor-disk"
        resources:
          requests:
            storage: 64Mi
