apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  annotations:
    workflows.argoproj.io/description: |
      checkout out from git, build and test a dotnet application.
    workflows.argoproj.io/maintainer: '@gals'
    workflows.argoproj.io/tags: dotnet, git
    workflows.argoproj.io/version: '>= 2.9.0'
  name: dotnet-build-dind
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: repo
        value: https://github.com/galsolom/testapp.git
      - name: branch
        value: main
      - name: tag
        value: 0.1
      - name: output
        value: argo-workflows-catalog
  templates:
    - name: main
      steps:
        - - name: buildandpush
            template: buildandpush
    - name: buildandpush
      container:
        image: docker:19.03.13
        command: [sh, -c]
        workingDir: /work
        args: ["docker build . -t test:{{workflow.parameters.tag}} && docker run --rm test:{{workflow.parameters.tag}};"]
        env:
        - name: DOCKER_HOST
          value: 127.0.0.1 # need to change to docker build machine ip;
        volumeMounts:
          - mountPath: /work
            name: work
      sidecars:
      - name: dind
        image: docker:19.03.13-dind
        securityContext:
          privileged: true
        mirrorVolumeMounts: true